"""End-to-end test: Generate a real lap debrief via Ollama."""
import asyncio
import numpy as np
import pandas as pd

from intelligence.alignment import DistanceAligner
from intelligence.corner_detector import CornerDetector
from intelligence.delta_engine import DeltaEngine
from intelligence.coach_engine import CoachEngine
from intelligence.report_generator import ReportGenerator

async def main():
    print("=== Live Ollama Lap Debrief Generation ===")
    print()

    # 1. Create synthetic telemetry
    n = 500
    dist = np.linspace(0, 5000, n)
    user_speed = 250 + 30 * np.sin(dist / 500)
    ghost_speed = user_speed + 5

    cols = {
        "distance_m": dist,
        "speed_kph": user_speed,
        "throttle": user_speed / 280,
        "brake": (280 - user_speed) / 280,
        "steer": np.random.uniform(-0.1, 0.1, n),
        "gear": np.clip((user_speed / 40).astype(int), 1, 8),
        "rpm": (user_speed * 40).astype(int),
        "drs": user_speed > 250,
        "x": np.cumsum(np.cos(np.linspace(0, 2 * np.pi, n))),
        "y": np.cumsum(np.sin(np.linspace(0, 2 * np.pi, n))),
        "z": np.zeros(n),
    }
    user_df = pd.DataFrame(cols)
    ghost_df = user_df.copy()
    ghost_df["speed_kph"] = ghost_speed

    # 2. Run intelligence pipeline
    aligner = DistanceAligner(grid_points=1000)
    ua, ga = aligner.align(user_df, ghost_df)

    detector = CornerDetector()
    uc = detector.detect(ua)
    gc = detector.detect(ga)

    engine = DeltaEngine()
    delta = engine.compute(ua, ga, uc, gc)

    coach = CoachEngine()
    tips = coach.analyze(delta, uc, gc)

    print(f"Pipeline: delta={delta.total_time_delta_ms:+.0f}ms, corners={uc.total_corners}, tips={len(tips)}")
    print()

    # 3. Generate report via Ollama
    gen = ReportGenerator()
    print(f"Backend: {gen.active_backend} ({gen.backend_info})")
    print()
    print("Generating report (this may take 30-60s on local LLM)...")
    print()

    report = await gen.generate_lap_debrief(
        delta=delta,
        user_corners=uc,
        ghost_corners=gc,
        coaching_tips=tips,
        track_name="Bahrain",
        driver_code="VER",
    )

    print(f"Title: {report.title}")
    print(f"Generated by: {report.generated_by}")
    print(f"Summary: {report.summary}")
    print(f"Key findings: {len(report.key_findings)}")
    print()
    print("--- FULL REPORT ---")
    print(report.markdown[:2000])
    if len(report.markdown) > 2000:
        print(f"\n... ({len(report.markdown)} total chars)")
    print("--- END ---")

asyncio.run(main())
