/**
 * ReportView — Displays a generated LapReport with markdown rendering
 */

"use client";

import { motion } from "framer-motion";
import { Zap, CheckCircle, Save, Loader2 } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { Panel } from "@/components/f1/primitives/Panel";
import { Badge } from "@/components/f1/primitives/Badge";
import type { LapReport } from "@/lib/api/intelligence";

const MD_COMPONENTS = {
  h1: ({ children }: any) => (
    <h1 className="text-2xl font-black text-gold mb-4 mt-6" style={{ fontFamily: "var(--font-rajdhani)" }}>{children}</h1>
  ),
  h2: ({ children }: any) => (
    <h2 className="text-xl font-bold text-white mb-3 mt-5">{children}</h2>
  ),
  h3: ({ children }: any) => (
    <h3 className="text-lg font-bold text-silver mb-2 mt-4">{children}</h3>
  ),
  p: ({ children }: any) => (
    <p className="text-silver/90 mb-3 leading-relaxed">{children}</p>
  ),
  ul: ({ children }: any) => (
    <ul className="list-disc list-inside space-y-1 mb-3 text-silver/90">{children}</ul>
  ),
  li: ({ children }: any) => <li className="ml-4">{children}</li>,
  strong: ({ children }: any) => (
    <strong className="text-gold font-bold">{children}</strong>
  ),
  code: ({ children }: any) => (
    <code className="bg-white/10 px-1.5 py-0.5 rounded text-gold font-mono text-sm">
      {children}
    </code>
  ),
  table: ({ children }: any) => (
    <table className="w-full border-collapse border border-white/20 my-4">{children}</table>
  ),
  th: ({ children }: any) => (
    <th className="border border-white/20 px-3 py-2 bg-white/5 text-gold font-bold text-left">
      {children}
    </th>
  ),
  td: ({ children }: any) => (
    <td className="border border-white/20 px-3 py-2 text-silver">{children}</td>
  ),
};

interface ReportViewProps {
  report:    LapReport;
  onSave:    () => void;
  isSaving?: boolean;
}

export function ReportView({ report, onSave, isSaving }: ReportViewProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -16 }}
      transition={{ duration: 0.4 }}
    >
      <Panel title={report.title}>
        {/* Header row */}
        <div className="flex items-center justify-between mb-4 pb-3 border-b border-white/10">
          <div className="flex items-center gap-2">
            <Zap size={14} className="text-gold" />
            <span className="text-xs text-silver/60">
              Generated by{" "}
              <span className="text-gold font-mono">{report.generated_by}</span>
            </span>
          </div>
          <button
            onClick={onSave}
            disabled={isSaving}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-gold/15 hover:bg-gold/25 disabled:opacity-50 border border-gold/40 rounded text-gold text-xs font-bold transition-all"
          >
            {isSaving
              ? <><Loader2 size={11} className="animate-spin" /> SAVING...</>
              : <><Save size={11} /> SAVE</>}
          </button>
        </div>

        {/* Summary */}
        <div className="mb-5 p-4 bg-white/5 rounded border border-gold/20">
          <div className="text-[10px] text-gold font-black mb-2 tracking-widest uppercase">
            Executive Summary
          </div>
          <p className="text-white text-sm leading-relaxed">{report.summary}</p>
        </div>

        {/* Key findings */}
        {report.key_findings.length > 0 && (
          <div className="mb-5">
            <div className="text-[10px] text-gold font-black mb-2 tracking-widest uppercase">
              Key Findings
            </div>
            <ul className="flex flex-col gap-1.5">
              {report.key_findings.map((f, i) => (
                <li key={i} className="flex items-start gap-2">
                  <CheckCircle size={14} className="text-green-500 mt-0.5 shrink-0" />
                  <span className="text-silver text-sm">{f}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Full markdown report */}
        <div className="prose prose-invert prose-sm max-w-none border-t border-white/10 pt-4">
          <ReactMarkdown components={MD_COMPONENTS}>
            {report.markdown}
          </ReactMarkdown>
        </div>
      </Panel>
    </motion.div>
  );
}
