"""
Report Generator
=================

Generates post-race debrief reports using an LLM backend.

Backend Priority Chain:
    1. OLLAMA  (local, free, no network) — if Ollama is running
    2. GEMINI  (cloud, free tier)        — if GEMINI_API_KEY is set
    3. TEMPLATE (offline, rule-based)    — always available

The report generator constructs structured prompts from telemetry
data and feeds them to whichever backend is available. The prompt
engineering is shared across all backends.

Report Types:
    1. LAP_DEBRIEF  — Single-lap deep analysis
    2. RACE_SUMMARY — Full race / session overview
    3. CORNER_STUDY — Deep dive into a specific corner

Usage:
    from intelligence.report_generator import ReportGenerator

    # Auto-detects Ollama → Gemini → Template
    gen = ReportGenerator()
    report = await gen.generate_lap_debrief(delta, corners, profile)
    print(report.markdown)

    # Force a specific backend
    gen = ReportGenerator(backend="ollama", ollama_model="gpt-oss:20b")
"""

import logging
import os
import httpx
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from .coach_engine import CoachingTip
from .corner_detector import CornerMap
from .delta_engine import DeltaResult
from .hardware_profiler import HardwareProfile

logger = logging.getLogger("APXIQ.Intelligence.ReportGenerator")


# =========================================================================
# Enums & Data Classes
# =========================================================================

class ReportType(Enum):
    """Types of reports the generator can produce."""
    LAP_DEBRIEF = "lap_debrief"
    RACE_SUMMARY = "race_summary"
    CORNER_STUDY = "corner_study"


@dataclass
class DebriefReport:
    """Generated debrief report."""

    report_type: ReportType
    title: str
    markdown: str               # Full report in markdown format
    summary: str                # One-paragraph executive summary
    key_findings: list[str]     # Bullet-point key findings
    generated_by: str           # "gemini", "local_template", etc.
    metadata: dict = field(default_factory=dict)

    @property
    def is_ai_generated(self) -> bool:
        """True if this report was generated by an LLM."""
        return self.generated_by != "local_template"


# =========================================================================
# Report Generator
# =========================================================================

class ReportGenerator:
    """
    Generates structured debrief reports from telemetry analysis.

    Supports three backends with automatic fallback:
        1. Ollama  — Local LLM (free, private, no network)
        2. Gemini  — Google's cloud API (free tier)
        3. Template — Rule-based local generation (always available)

    The backend is auto-detected at init time. You can also force
    a specific backend via the `backend` parameter.
    """

    # Ollama configuration
    OLLAMA_BASE_URL = "http://localhost:11434"
    OLLAMA_DEFAULT_MODEL = "gpt-oss:20b"

    def __init__(
        self,
        backend: Optional[str] = None,
        ollama_model: Optional[str] = None,
        ollama_url: Optional[str] = None,
        gemini_api_key: Optional[str] = None,
    ):
        """
        Args:
            backend: Force a specific backend: "ollama", "gemini", or "template".
                     If None, auto-detects in priority order.
            ollama_model: Ollama model name (default: gpt-oss:20b).
            ollama_url: Ollama API base URL (default: http://localhost:11434).
            gemini_api_key: Gemini API key. If None, tries GEMINI_API_KEY env var.
        """
        self._active_backend = "template"  # Safe default
        self._ollama_model = ollama_model or self.OLLAMA_DEFAULT_MODEL
        self._ollama_url = ollama_url or self.OLLAMA_BASE_URL
        self._gemini_client = None
        self._gemini_model = "gemini-2.0-flash"

        if backend:
            # User forced a specific backend
            self._setup_forced_backend(backend, gemini_api_key)
        else:
            # Auto-detect: Ollama → Gemini → Template
            self._auto_detect_backend(gemini_api_key)

        logger.info(
            f"ReportGenerator initialized: backend={self._active_backend}"
            + (f", model={self._ollama_model}" if self._active_backend == "ollama" else "")
            + (f", model={self._gemini_model}" if self._active_backend == "gemini" else "")
        )

    def _setup_forced_backend(self, backend: str, gemini_api_key: Optional[str]):
        """Configure a user-specified backend."""
        if backend == "ollama":
            if self._check_ollama():
                self._active_backend = "ollama"
            else:
                logger.warning("Ollama requested but not reachable. Falling back.")
                self._auto_detect_backend(gemini_api_key)
        elif backend == "gemini":
            if self._setup_gemini(gemini_api_key):
                self._active_backend = "gemini"
            else:
                logger.warning("Gemini requested but not available. Falling back.")
                self._active_backend = "template"
        else:
            self._active_backend = "template"

    def _auto_detect_backend(self, gemini_api_key: Optional[str]):
        """Auto-detect the best available backend."""
        # Priority 1: Ollama (local)
        if self._check_ollama():
            self._active_backend = "ollama"
            logger.info(f"Auto-detected Ollama at {self._ollama_url}")
            return

        # Priority 2: Gemini (cloud)
        if self._setup_gemini(gemini_api_key):
            self._active_backend = "gemini"
            return

        # Priority 3: Template (always available)
        self._active_backend = "template"
        logger.info("No LLM backends available. Using template mode.")

    def _check_ollama(self) -> bool:
        """Check if Ollama is running and the model is available."""
        try:
            resp = httpx.get(f"{self._ollama_url}/api/tags", timeout=2.0)
            if resp.status_code == 200:
                models = resp.json().get("models", [])
                available = [m["name"] for m in models]
                if self._ollama_model in available:
                    return True
                # Try without tag suffix (e.g., "gpt-oss:20b" → check "gpt-oss")
                base_names = [m["name"].split(":")[0] for m in models]
                if self._ollama_model.split(":")[0] in base_names:
                    # Find the full name
                    for m in models:
                        if m["name"].startswith(self._ollama_model.split(":")[0]):
                            self._ollama_model = m["name"]
                            return True
                logger.warning(
                    f"Ollama running but model '{self._ollama_model}' not found. "
                    f"Available: {available}"
                )
            return False
        except Exception:
            return False

    def _setup_gemini(self, api_key: Optional[str]) -> bool:
        """Try to set up the Gemini client."""
        key = api_key or os.environ.get("GEMINI_API_KEY")
        if not key:
            return False
        try:
            from google import genai
            self._gemini_client = genai.Client(api_key=key)
            logger.info("Gemini API configured successfully")
            return True
        except ImportError:
            logger.warning("google-genai not installed. Skipping Gemini.")
            return False
        except Exception as e:
            logger.warning(f"Gemini setup failed: {e}")
            return False

    @property
    def active_backend(self) -> str:
        """The currently active backend: 'ollama', 'gemini', or 'template'."""
        return self._active_backend

    @property
    def ai_available(self) -> bool:
        """True if an AI backend (Ollama or Gemini) is active."""
        return self._active_backend in ("ollama", "gemini")

    @property
    def backend_info(self) -> dict:
        """Detailed info about the active backend."""
        info = {"backend": self._active_backend}
        if self._active_backend == "ollama":
            info["model"] = self._ollama_model
            info["url"] = self._ollama_url
        elif self._active_backend == "gemini":
            info["model"] = self._gemini_model
        return info

    # -----------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------

    async def generate_lap_debrief(
        self,
        delta: DeltaResult,
        user_corners: CornerMap,
        ghost_corners: CornerMap,
        coaching_tips: list[CoachingTip],
        hardware: Optional[HardwareProfile] = None,
        track_name: str = "Unknown Track",
        driver_code: str = "VER",
    ) -> DebriefReport:
        """
        Generate a detailed single-lap debrief report.

        Args:
            delta: DeltaResult from the lap comparison.
            user_corners: User's corner map.
            ghost_corners: Ghost corner map.
            coaching_tips: Tips from the CoachEngine.
            hardware: Detected hardware profile.
            track_name: Name of the track.
            driver_code: Ghost driver code for reference.

        Returns:
            DebriefReport with full markdown analysis.
        """
        # Build the structured data payload for the prompt
        data = self._build_lap_data(
            delta, user_corners, ghost_corners,
            coaching_tips, hardware, track_name, driver_code,
        )

        if self.ai_available:
            return await self._generate_ai_report(
                ReportType.LAP_DEBRIEF, data
            )
        else:
            return self._generate_template_report(
                ReportType.LAP_DEBRIEF, data
            )

    async def generate_race_summary(
        self,
        lap_deltas: list[DeltaResult],
        final_position: int,
        total_laps: int,
        track_name: str = "Unknown Track",
        coaching_tips: list[CoachingTip] = None,
    ) -> DebriefReport:
        """
        Generate a full race/session summary report.

        Args:
            lap_deltas: List of DeltaResults for each lap.
            final_position: Final race position.
            total_laps: Total laps completed.
            track_name: Track name.
            coaching_tips: Accumulated tips from the session.

        Returns:
            DebriefReport with race overview.
        """
        import numpy as np

        data = {
            "track_name": track_name,
            "total_laps": total_laps,
            "final_position": final_position,
            "total_time_deltas": [d.total_time_delta_ms for d in lap_deltas],
            "avg_lap_delta_ms": float(np.mean(
                [d.total_time_delta_ms for d in lap_deltas]
            )) if lap_deltas else 0.0,
            "best_lap_delta_ms": float(min(
                [d.total_time_delta_ms for d in lap_deltas]
            )) if lap_deltas else 0.0,
            "worst_lap_delta_ms": float(max(
                [d.total_time_delta_ms for d in lap_deltas]
            )) if lap_deltas else 0.0,
            "tip_count": len(coaching_tips) if coaching_tips else 0,
        }

        if self.ai_available:
            return await self._generate_ai_report(
                ReportType.RACE_SUMMARY, data
            )
        else:
            return self._generate_template_report(
                ReportType.RACE_SUMMARY, data
            )

    # -----------------------------------------------------------------
    # AI Generation (Multi-Backend)
    # -----------------------------------------------------------------

    async def _generate_ai_report(
        self, report_type: ReportType, data: dict
    ) -> DebriefReport:
        """Route to the active AI backend."""
        prompt = self._build_prompt(report_type, data)

        try:
            if self._active_backend == "ollama":
                markdown = await self._call_ollama(prompt)
                backend_label = f"ollama/{self._ollama_model}"
            elif self._active_backend == "gemini":
                markdown = await self._call_gemini(prompt)
                backend_label = f"gemini/{self._gemini_model}"
            else:
                return self._generate_template_report(report_type, data)

            summary, findings = self._parse_ai_response(markdown)

            return DebriefReport(
                report_type=report_type,
                title=self._get_title(report_type, data),
                markdown=markdown,
                summary=summary,
                key_findings=findings,
                generated_by=backend_label,
                metadata={"backend": self._active_backend, "data": data},
            )

        except Exception as e:
            logger.error(f"AI generation failed ({self._active_backend}): {e}")
            logger.info("Falling back to template mode.")
            return self._generate_template_report(report_type, data)

    async def _call_ollama(self, prompt: str) -> str:
        """
        Call the Ollama REST API for text generation.

        Uses the /api/generate endpoint with streaming disabled
        for simplicity. The model runs locally — no network needed.
        """
        async with httpx.AsyncClient(timeout=120.0) as client:
            response = await client.post(
                f"{self._ollama_url}/api/generate",
                json={
                    "model": self._ollama_model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {
                        "temperature": 0.7,
                        "top_p": 0.9,
                        "num_predict": 2048,
                    },
                },
            )
            response.raise_for_status()
            result = response.json()
            return result.get("response", "")

    async def _call_gemini(self, prompt: str) -> str:
        """Call the Gemini API for text generation."""
        response = self._gemini_client.models.generate_content(
            model=self._gemini_model,
            contents=prompt,
        )
        return response.text

    def _build_prompt(self, report_type: ReportType, data: dict) -> str:
        """Build the structured prompt for the LLM."""

        if report_type == ReportType.LAP_DEBRIEF:
            return f"""You are an expert Formula 1 race engineer providing a post-lap debrief to a sim racer.

## Context
- Track: {data['track_name']}
- Ghost reference: {data['driver_code']}'s fastest lap
- Hardware: {data.get('hardware_type', 'Unknown')}
- Total time delta: {data['total_delta_ms']:+.0f}ms ({data['total_delta_ms']/1000:+.3f}s)
- Average speed difference: {data['avg_speed_delta']:.1f} km/h

## Corner-by-Corner Analysis
{data['corner_summary']}

## Coaching Tips Already Identified
{data['tips_text']}

## Time Loss Regions
{data['loss_regions_text']}

## Instructions
Generate a detailed, professional debrief report in markdown format. Include:
1. **Executive Summary** — One paragraph overview of lap performance
2. **Corner Analysis** — Go through the most impactful corners
3. **Braking Performance** — Analyze brake point accuracy
4. **Throttle Application** — Where throttle usage can improve
5. **Key Takeaways** — 3-5 bullet-point actionable items for the next lap

Use a professional but encouraging tone. Reference specific corner numbers and concrete numbers (km/h, meters, milliseconds).
Scale your expectations to the driver's hardware ({data.get('hardware_type', 'Unknown')}).
"""

        elif report_type == ReportType.RACE_SUMMARY:
            return f"""You are an expert Formula 1 race engineer providing a post-race debrief.

## Race Data
- Track: {data['track_name']}
- Laps completed: {data['total_laps']}
- Final position: P{data['final_position']}
- Average lap delta vs ghost: {data['avg_lap_delta_ms']:+.0f}ms
- Best lap delta: {data['best_lap_delta_ms']:+.0f}ms
- Worst lap delta: {data['worst_lap_delta_ms']:+.0f}ms
- Total coaching tips generated: {data['tip_count']}

## Instructions
Generate a race summary report in markdown format. Include:
1. **Race Overview** — High-level performance summary
2. **Consistency Analysis** — Lap-to-lap variation
3. **Progress Trend** — Did the driver improve over the session?
4. **Areas for Improvement** — Top 3 priorities
5. **Positive Highlights** — What went well

Keep it concise, data-driven, and actionable.
"""

        return "Generate a telemetry analysis report."

    def _parse_ai_response(
        self, markdown: str
    ) -> tuple[str, list[str]]:
        """Extract summary and key findings from AI-generated markdown."""
        lines = markdown.strip().split("\n")

        # Summary = first non-empty, non-heading paragraph
        summary = ""
        for line in lines:
            stripped = line.strip()
            if stripped and not stripped.startswith("#"):
                summary = stripped
                break

        # Key findings = lines starting with "- " or "* " under takeaways section
        findings = []
        in_takeaways = False
        for line in lines:
            stripped = line.strip()
            if "takeaway" in stripped.lower() or "key" in stripped.lower():
                in_takeaways = True
                continue
            if in_takeaways and stripped.startswith(("- ", "* ", "• ")):
                findings.append(stripped.lstrip("-*• ").strip())
            elif in_takeaways and stripped.startswith("#"):
                in_takeaways = False  # Hit next section

        return summary, findings[:5]

    # -----------------------------------------------------------------
    # Template Generation (Offline Fallback)
    # -----------------------------------------------------------------

    def _generate_template_report(
        self, report_type: ReportType, data: dict
    ) -> DebriefReport:
        """Generate a report using local templates (no LLM needed)."""

        if report_type == ReportType.LAP_DEBRIEF:
            return self._template_lap_debrief(data)
        elif report_type == ReportType.RACE_SUMMARY:
            return self._template_race_summary(data)
        else:
            return DebriefReport(
                report_type=report_type,
                title="Analysis Report",
                markdown="*Report generation not available for this type.*",
                summary="No report available.",
                key_findings=[],
                generated_by="local_template",
            )

    def _template_lap_debrief(self, data: dict) -> DebriefReport:
        """Template-based lap debrief."""
        total_ms = data["total_delta_ms"]
        delta_sign = "behind" if total_ms > 0 else "ahead of"
        delta_abs = abs(total_ms)

        # Build corner analysis section
        corner_section = data.get("corner_summary", "No corner data available.")

        # Build tips section
        tips_section = data.get("tips_text", "No coaching tips available.")

        markdown = f"""# Lap Debrief — {data['track_name']}

## Executive Summary

Your lap was **{delta_abs/1000:.3f}s {delta_sign}** the ghost reference
({data['driver_code']}'s fastest lap). Average speed difference:
**{data['avg_speed_delta']:+.1f} km/h**.
Hardware detected: **{data.get('hardware_type', 'Unknown')}**.

---

## Corner-by-Corner Breakdown

{corner_section}

---

## Coaching Notes

{tips_section}

---

## Key Takeaways

"""
        # Generate findings from coaching tips
        findings = []
        if data.get("top_tips"):
            for i, tip in enumerate(data["top_tips"][:5], 1):
                findings.append(tip)
                markdown += f"- {tip}\n"
        else:
            default_finding = (
                f"Overall delta of {delta_abs/1000:.3f}s — "
                f"focus on the biggest time-loss zones."
            )
            findings.append(default_finding)
            markdown += f"- {default_finding}\n"

        summary = (
            f"Lap delta: {delta_abs/1000:.3f}s {delta_sign} ghost "
            f"({data['driver_code']}). "
            f"Avg speed diff: {data['avg_speed_delta']:+.1f} km/h."
        )

        return DebriefReport(
            report_type=ReportType.LAP_DEBRIEF,
            title=f"Lap Debrief — {data['track_name']}",
            markdown=markdown,
            summary=summary,
            key_findings=findings,
            generated_by="local_template",
            metadata=data,
        )

    def _template_race_summary(self, data: dict) -> DebriefReport:
        """Template-based race summary."""
        markdown = f"""# Race Summary — {data['track_name']}

## Overview

| Metric | Value |
|---|---|
| Final Position | P{data['final_position']} |
| Laps Completed | {data['total_laps']} |
| Avg Delta vs Ghost | {data['avg_lap_delta_ms']:+.0f}ms |
| Best Lap Delta | {data['best_lap_delta_ms']:+.0f}ms |
| Worst Lap Delta | {data['worst_lap_delta_ms']:+.0f}ms |
| Coaching Tips | {data['tip_count']} |

## Analysis

Average lap delta of **{data['avg_lap_delta_ms']:+.0f}ms** vs ghost reference.
Best lap was **{data['best_lap_delta_ms']:+.0f}ms** and worst was
**{data['worst_lap_delta_ms']:+.0f}ms**, giving a consistency range of
**{abs(data['worst_lap_delta_ms'] - data['best_lap_delta_ms']):.0f}ms**.
"""
        findings = [
            f"Finished P{data['final_position']}",
            f"Average delta: {data['avg_lap_delta_ms']:+.0f}ms vs ghost",
            f"Consistency range: {abs(data['worst_lap_delta_ms'] - data['best_lap_delta_ms']):.0f}ms",
        ]

        return DebriefReport(
            report_type=ReportType.RACE_SUMMARY,
            title=f"Race Summary — {data['track_name']}",
            markdown=markdown,
            summary=f"Finished P{data['final_position']} with avg delta {data['avg_lap_delta_ms']:+.0f}ms.",
            key_findings=findings,
            generated_by="local_template",
            metadata=data,
        )

    # -----------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------

    def _build_lap_data(
        self,
        delta: DeltaResult,
        user_corners: CornerMap,
        ghost_corners: CornerMap,
        tips: list[CoachingTip],
        hardware: Optional[HardwareProfile],
        track_name: str,
        driver_code: str,
    ) -> dict:
        """Build structured data dict from analysis objects."""
        from .delta_engine import DeltaEngine

        # Corner summary
        corner_lines = []
        for uc in user_corners.corners:
            gc = ghost_corners.get_corner_at_distance(
                uc.apex_distance_m, tolerance_m=100.0
            )
            if gc:
                speed_diff = uc.apex_speed_kph - gc.apex_speed_kph
                corner_lines.append(
                    f"- **T{uc.index}** ({uc.classification}): "
                    f"Apex {uc.apex_speed_kph:.0f} km/h "
                    f"(ghost: {gc.apex_speed_kph:.0f}, "
                    f"delta: {speed_diff:+.0f} km/h)"
                )
            else:
                corner_lines.append(
                    f"- **T{uc.index}** ({uc.classification}): "
                    f"Apex {uc.apex_speed_kph:.0f} km/h (no ghost match)"
                )

        # Tips text
        tip_lines = []
        top_tips = []
        for tip in sorted(tips, key=lambda t: t.priority, reverse=True):
            tip_lines.append(f"- [{tip.severity.value.upper()}] {tip.message}")
            top_tips.append(tip.message)

        # Time loss regions
        engine = DeltaEngine()
        loss_regions = engine.get_time_loss_regions(delta, threshold_ms=30.0)
        loss_lines = []
        for r in loss_regions[:5]:
            loss_lines.append(
                f"- {r['start_m']:.0f}m → {r['end_m']:.0f}m: "
                f"{r['time_lost_ms']:.0f}ms lost"
            )

        return {
            "track_name": track_name,
            "driver_code": driver_code,
            "hardware_type": hardware.tier_label if hardware else "Unknown",
            "total_delta_ms": delta.total_time_delta_ms,
            "avg_speed_delta": delta.avg_speed_delta_kph,
            "corner_summary": "\n".join(corner_lines) or "No corners detected.",
            "tips_text": "\n".join(tip_lines) or "No tips generated.",
            "top_tips": top_tips[:5],
            "loss_regions_text": "\n".join(loss_lines) or "No significant time-loss regions.",
            "total_corners": user_corners.total_corners,
            "worst_corner": delta.worst_corner_index,
            "best_corner": delta.best_corner_index,
        }

    def _get_title(self, report_type: ReportType, data: dict) -> str:
        """Generate report title."""
        track = data.get("track_name", "Unknown")
        if report_type == ReportType.LAP_DEBRIEF:
            return f"Lap Debrief — {track}"
        elif report_type == ReportType.RACE_SUMMARY:
            return f"Race Summary — {track}"
        return f"Analysis — {track}"
